import type { AutocompleteOption } from "@skeletonlabs/skeleton";

export const categoryOptions: string[] = ['general', 'science', 'sports', 'business', 'health', 'entertainment', 'tech', 'politics', 'food', 'travel'];

export const countryOptions: AutocompleteOption<string>[] = [{ value: "ar", label: "Argentina" },
{ value: "am", label: "Armenia" },
{ value: "au", label: "Australia" },
{ value: "at", label: "Austria" },
{ value: "by", label: "Belarus" },
{ value: "be", label: "Belgium" },
{ value: "bo", label: "Bolivia" },
{ value: "br", label: "Brazil" },
{ value: "bg", label: "Bulgaria" },
{ value: "ca", label: "Canada" },
{ value: "cl", label: "Chile" },
{ value: "cn", label: "China" },
{ value: "co", label: "Colombia" },
{ value: "hr", label: "Croatia" },
{ value: "cz", label: "Czechia" },
{ value: "ec", label: "Ecuador" },
{ value: "eg", label: "Egypt" },
{ value: "fr", label: "France" },
{ value: "de", label: "Germany" },
{ value: "gr", label: "Greece" },
{ value: "hn", label: "Honduras" },
{ value: "hk", label: "Hong Kong" },
{ value: "in", label: "India" },
{ value: "id", label: "Indonesia" },
{ value: "ir", label: "Iran" },
{ value: "ie", label: "Ireland" },
{ value: "il", label: "Israel" },
{ value: "it", label: "Italy" },
{ value: "jp", label: "Japan" },
{ value: "kr", label: "Korea" },
{ value: "mx", label: "Mexico" },
{ value: "nl", label: "Netherlands" },
{ value: "nz", label: "New Zealand" },
{ value: "ni", label: "Nicaragua" },
{ value: "pk", label: "Pakistan" },
{ value: "pa", label: "Panama" },
{ value: "pe", label: "Peru" },
{ value: "pl", label: "Poland" },
{ value: "pt", label: "Portugal" },
{ value: "qa", label: "Qatar" },
{ value: "ro", label: "Romania" },
{ value: "ru", label: "Russia" },
{ value: "sa", label: "Saudi Arabia" },
{ value: "za", label: "South Africa" },
{ value: "es", label: "Spain" },
{ value: "ch", label: "Switzerland" },
{ value: "sy", label: "Syria" },
{ value: "tw", label: "Taiwan" },
{ value: "th", label: "Thailand" },
{ value: "tr", label: "Turkey" },
{ value: "ua", label: "Ukraine" },
{ value: "gb", label: "United Kingdom" },
{ value: "us", label: "United States Of America" },
{ value: "uy", label: "Uruguay" },
{ value: "ve", label: "Venezuela" }]